package com.scott.ezmessaging.contentresolver

/**
 * Actual SMS data pulled from device
 */
object TestContentResolverDataSMS {

    val RECEIVED = listOf(
        TestCursorObject(
            listOf(
                TestCursorColumnEntry(columnName = "_id", value = "55264"),
                TestCursorColumnEntry(columnName = "thread_id", value = "482"),
                TestCursorColumnEntry(columnName = "address", value = "49878"),
                TestCursorColumnEntry(columnName = "person", value = null),
                TestCursorColumnEntry(columnName = "date", value = "1711491255707"),
                TestCursorColumnEntry(columnName = "date_sent", value = "1711491254000"),
                TestCursorColumnEntry(columnName = "protocol", value = "0"),
                TestCursorColumnEntry(columnName = "read", value = "1"),
                TestCursorColumnEntry(columnName = "status", value = "-1"),
                TestCursorColumnEntry(columnName = "type", value = "1"),
                TestCursorColumnEntry(columnName = "reply_path_present", value = "0"),
                TestCursorColumnEntry(columnName = "subject", value = null),
                TestCursorColumnEntry(columnName = "body", value = "All or part of your Samsung order #SA131757595 was delivered. Thank you for choosing Samsung."),
                TestCursorColumnEntry(columnName = "service_center", value = null),
                TestCursorColumnEntry(columnName = "locked", value = "0"),
                TestCursorColumnEntry(columnName = "error_code", value = "0"),
                TestCursorColumnEntry(columnName = "sub_id", value = "1"),
                TestCursorColumnEntry(columnName = "creator", value = "com.google.android.apps.messaging"),
                TestCursorColumnEntry(columnName = "seen", value = "1"),
                TestCursorColumnEntry(columnName = "deletable", value = "0"),
                TestCursorColumnEntry(columnName = "sim_slot", value = "0"),
                TestCursorColumnEntry(columnName = "sim_imsi", value = null),
                TestCursorColumnEntry(columnName = "hidden", value = "0"),
                TestCursorColumnEntry(columnName = "group_id", value = null),
                TestCursorColumnEntry(columnName = "group_type", value = null),
                TestCursorColumnEntry(columnName = "delivery_date", value = null),
                TestCursorColumnEntry(columnName = "app_id", value = "0"),
                TestCursorColumnEntry(columnName = "msg_id", value = "0"),
                TestCursorColumnEntry(columnName = "callback_number", value = null),
                TestCursorColumnEntry(columnName = "reserved", value = "0"),
                TestCursorColumnEntry(columnName = "pri", value = "0"),
                TestCursorColumnEntry(columnName = "teleservice_id", value = "0"),
                TestCursorColumnEntry(columnName = "link_url", value = null),
                TestCursorColumnEntry(columnName = "svc_cmd", value = "0"),
                TestCursorColumnEntry(columnName = "svc_cmd_content", value = null),
                TestCursorColumnEntry(columnName = "roam_pending", value = "0"),
                TestCursorColumnEntry(columnName = "spam_report", value = "0"),
                TestCursorColumnEntry(columnName = "secret_mode", value = "0"),
                TestCursorColumnEntry(columnName = "safe_message", value = "0"),
                TestCursorColumnEntry(columnName = "favorite", value = "0"),
                TestCursorColumnEntry(columnName = "d_rpt_cnt", value = "0"),
                TestCursorColumnEntry(columnName = "using_mode", value = "0"),
                TestCursorColumnEntry(columnName = "from_address", value = null),
                TestCursorColumnEntry(columnName = "announcements_subtype", value = "0"),
                TestCursorColumnEntry(columnName = "announcements_scenario_id", value = null),
                TestCursorColumnEntry(columnName = "device_name", value = null),
                TestCursorColumnEntry(columnName = "correlation_tag", value = null),
                TestCursorColumnEntry(columnName = "object_id", value = null),
                TestCursorColumnEntry(columnName = "cmc_prop", value = null),
                TestCursorColumnEntry(columnName = "bin_info", value = "0"),
                TestCursorColumnEntry(columnName = "re_original_body", value = null),
                TestCursorColumnEntry(columnName = "re_body", value = null),
                TestCursorColumnEntry(columnName = "re_original_key", value = null),
                TestCursorColumnEntry(columnName = "re_recipient_address", value = null),
                TestCursorColumnEntry(columnName = "re_content_uri", value = null),
                TestCursorColumnEntry(columnName = "re_content_type", value = null),
                TestCursorColumnEntry(columnName = "re_file_name", value = null),
                TestCursorColumnEntry(columnName = "re_type", value = "0"),
                TestCursorColumnEntry(columnName = "re_count_info", value = null)
            )
        ),
        TestCursorObject(
            listOf(
                TestCursorColumnEntry(columnName = "_id", value = "55263"),
                TestCursorColumnEntry(columnName = "thread_id", value = "703"),
                TestCursorColumnEntry(columnName = "address", value = "8336430251"),
                TestCursorColumnEntry(columnName = "person", value = null),
                TestCursorColumnEntry(columnName = "date", value = "1711480912446"),
                TestCursorColumnEntry(columnName = "date_sent", value = "1711480911000"),
                TestCursorColumnEntry(columnName = "protocol", value = "0"),
                TestCursorColumnEntry(columnName = "read", value = "1"),
                TestCursorColumnEntry(columnName = "status", value = "-1"),
                TestCursorColumnEntry(columnName = "type", value = "1"),
                TestCursorColumnEntry(columnName = "reply_path_present", value = "0"),
                TestCursorColumnEntry(columnName = "subject", value = null),
                TestCursorColumnEntry(columnName = "body", value = "A package is ready for pickup at Package Concierge."),
                TestCursorColumnEntry(columnName = "service_center", value = null),
                TestCursorColumnEntry(columnName = "locked", value = "0"),
                TestCursorColumnEntry(columnName = "error_code", value = "0"),
                TestCursorColumnEntry(columnName = "sub_id", value = "1"),
                TestCursorColumnEntry(columnName = "creator", value = "com.google.android.apps.messaging"),
                TestCursorColumnEntry(columnName = "seen", value = "1"),
                TestCursorColumnEntry(columnName = "deletable", value = "0"),
                TestCursorColumnEntry(columnName = "sim_slot", value = "0"),
                TestCursorColumnEntry(columnName = "sim_imsi", value = null),
                TestCursorColumnEntry(columnName = "hidden", value = "0"),
                TestCursorColumnEntry(columnName = "group_id", value = null),
                TestCursorColumnEntry(columnName = "group_type", value = null),
                TestCursorColumnEntry(columnName = "delivery_date", value = null),
                TestCursorColumnEntry(columnName = "app_id", value = "0"),
                TestCursorColumnEntry(columnName = "msg_id", value = "0"),
                TestCursorColumnEntry(columnName = "callback_number", value = null),
                TestCursorColumnEntry(columnName = "reserved", value = "0"),
                TestCursorColumnEntry(columnName = "pri", value = "0"),
                TestCursorColumnEntry(columnName = "teleservice_id", value = "0"),
                TestCursorColumnEntry(columnName = "link_url", value = null),
                TestCursorColumnEntry(columnName = "svc_cmd", value = "0"),
                TestCursorColumnEntry(columnName = "svc_cmd_content", value = null),
                TestCursorColumnEntry(columnName = "roam_pending", value = "0"),
                TestCursorColumnEntry(columnName = "spam_report", value = "0"),
                TestCursorColumnEntry(columnName = "secret_mode", value = "0"),
                TestCursorColumnEntry(columnName = "safe_message", value = "0"),
                TestCursorColumnEntry(columnName = "favorite", value = "0"),
                TestCursorColumnEntry(columnName = "d_rpt_cnt", value = "0"),
                TestCursorColumnEntry(columnName = "using_mode", value = "0"),
                TestCursorColumnEntry(columnName = "from_address", value = null),
                TestCursorColumnEntry(columnName = "announcements_subtype", value = "0"),
                TestCursorColumnEntry(columnName = "announcements_scenario_id", value = null),
                TestCursorColumnEntry(columnName = "device_name", value = null),
                TestCursorColumnEntry(columnName = "correlation_tag", value = null),
                TestCursorColumnEntry(columnName = "object_id", value = null),
                TestCursorColumnEntry(columnName = "cmc_prop", value = null),
                TestCursorColumnEntry(columnName = "bin_info", value = "0"),
                TestCursorColumnEntry(columnName = "re_original_body", value = null),
                TestCursorColumnEntry(columnName = "re_body", value = null),
                TestCursorColumnEntry(columnName = "re_original_key", value = null),
                TestCursorColumnEntry(columnName = "re_recipient_address", value = null),
                TestCursorColumnEntry(columnName = "re_content_uri", value = null),
                TestCursorColumnEntry(columnName = "re_content_type", value = null),
                TestCursorColumnEntry(columnName = "re_file_name", value = null),
                TestCursorColumnEntry(columnName = "re_type", value = "0"),
                TestCursorColumnEntry(columnName = "re_count_info", value = null)
            )
        )
    )

    val SENT = listOf(
        TestCursorObject(
            listOf(
                TestCursorColumnEntry(columnName = "_id", value = "55255"),
                TestCursorColumnEntry(columnName = "thread_id", value = "38"),
                TestCursorColumnEntry(columnName = "address", value = "5555555555"),
                TestCursorColumnEntry(columnName = "person", value = null),
                TestCursorColumnEntry(columnName = "date", value = "1710892306823"),
                TestCursorColumnEntry(columnName = "date_sent", value = "0"),
                TestCursorColumnEntry(columnName = "protocol", value = null),
                TestCursorColumnEntry(columnName = "read", value = "1"),
                TestCursorColumnEntry(columnName = "status", value = "-1"),
                TestCursorColumnEntry(columnName = "type", value = "2"),
                TestCursorColumnEntry(columnName = "reply_path_present", value = null),
                TestCursorColumnEntry(columnName = "subject", value = null),
                TestCursorColumnEntry(columnName = "body", value = "hiiii"),
                TestCursorColumnEntry(columnName = "service_center", value = null),
                TestCursorColumnEntry(columnName = "locked", value = "0"),
                TestCursorColumnEntry(columnName = "error_code", value = "-1"),
                TestCursorColumnEntry(columnName = "sub_id", value = "1"),
                TestCursorColumnEntry(columnName = "creator", value = "com.google.android.apps.messaging"),
                TestCursorColumnEntry(columnName = "seen", value = "1"),
                TestCursorColumnEntry(columnName = "deletable", value = "0"),
                TestCursorColumnEntry(columnName = "sim_slot", value = "0"),
                TestCursorColumnEntry(columnName = "sim_imsi", value = null),
                TestCursorColumnEntry(columnName = "hidden", value = "0"),
                TestCursorColumnEntry(columnName = "group_id", value = null),
                TestCursorColumnEntry(columnName = "group_type", value = null),
                TestCursorColumnEntry(columnName = "delivery_date", value = null),
                TestCursorColumnEntry(columnName = "app_id", value = "0"),
                TestCursorColumnEntry(columnName = "msg_id", value = "0"),
                TestCursorColumnEntry(columnName = "callback_number", value = null),
                TestCursorColumnEntry(columnName = "reserved", value = "0"),
                TestCursorColumnEntry(columnName = "pri", value = "0"),
                TestCursorColumnEntry(columnName = "teleservice_id", value = "0"),
                TestCursorColumnEntry(columnName = "link_url", value = null),
                TestCursorColumnEntry(columnName = "svc_cmd", value = "0"),
                TestCursorColumnEntry(columnName = "svc_cmd_content", value = null),
                TestCursorColumnEntry(columnName = "roam_pending", value = "0"),
                TestCursorColumnEntry(columnName = "spam_report", value = "0"),
                TestCursorColumnEntry(columnName = "secret_mode", value = "0"),
                TestCursorColumnEntry(columnName = "safe_message", value = "0"),
                TestCursorColumnEntry(columnName = "favorite", value = "0"),
                TestCursorColumnEntry(columnName = "d_rpt_cnt", value = "0"),
                TestCursorColumnEntry(columnName = "using_mode", value = "0"),
                TestCursorColumnEntry(columnName = "from_address", value = null),
                TestCursorColumnEntry(columnName = "announcements_subtype", value = "0"),
                TestCursorColumnEntry(columnName = "announcements_scenario_id", value = null),
                TestCursorColumnEntry(columnName = "device_name", value = null),
                TestCursorColumnEntry(columnName = "correlation_tag", value = null),
                TestCursorColumnEntry(columnName = "object_id", value = null),
                TestCursorColumnEntry(columnName = "cmc_prop", value = null),
                TestCursorColumnEntry(columnName = "bin_info", value = "0"),
                TestCursorColumnEntry(columnName = "re_original_body", value = null),
                TestCursorColumnEntry(columnName = "re_body", value = null),
                TestCursorColumnEntry(columnName = "re_original_key", value = null),
                TestCursorColumnEntry(columnName = "re_recipient_address", value = null),
                TestCursorColumnEntry(columnName = "re_content_uri", value = null),
                TestCursorColumnEntry(columnName = "re_content_type", value = null),
                TestCursorColumnEntry(columnName = "re_file_name", value = null),
                TestCursorColumnEntry(columnName = "re_type", value = "0"),
                TestCursorColumnEntry(columnName = "re_count_info", value = null)
            )
        ),
        TestCursorObject(
            listOf(
                TestCursorColumnEntry(columnName = "_id", value = "55218"),
                TestCursorColumnEntry(columnName = "thread_id", value = "11"),
                TestCursorColumnEntry(columnName = "address", value = "+12222222222"),
                TestCursorColumnEntry(columnName = "person", value = null),
                TestCursorColumnEntry(columnName = "date", value = "1710442650402"),
                TestCursorColumnEntry(columnName = "date_sent", value = "0"),
                TestCursorColumnEntry(columnName = "protocol", value = null),
                TestCursorColumnEntry(columnName = "read", value = "1"),
                TestCursorColumnEntry(columnName = "status", value = "-1"),
                TestCursorColumnEntry(columnName = "type", value = "2"),
                TestCursorColumnEntry(columnName = "reply_path_present", value = null),
                TestCursorColumnEntry(columnName = "subject", value = null),
                TestCursorColumnEntry(columnName = "body", value = "Hope you bought me a pie"),
                TestCursorColumnEntry(columnName = "service_center", value = null),
                TestCursorColumnEntry(columnName = "locked", value = "0"),
                TestCursorColumnEntry(columnName = "error_code", value = "-1"),
                TestCursorColumnEntry(columnName = "sub_id", value = "1"),
                TestCursorColumnEntry(columnName = "creator", value = "com.google.android.apps.messaging"),
                TestCursorColumnEntry(columnName = "seen", value = "1"),
                TestCursorColumnEntry(columnName = "deletable", value = "0"),
                TestCursorColumnEntry(columnName = "sim_slot", value = "0"),
                TestCursorColumnEntry(columnName = "sim_imsi", value = null),
                TestCursorColumnEntry(columnName = "hidden", value = "0"),
                TestCursorColumnEntry(columnName = "group_id", value = null),
                TestCursorColumnEntry(columnName = "group_type", value = null),
                TestCursorColumnEntry(columnName = "delivery_date", value = null),
                TestCursorColumnEntry(columnName = "app_id", value = "0"),
                TestCursorColumnEntry(columnName = "msg_id", value = "0"),
                TestCursorColumnEntry(columnName = "callback_number", value = null),
                TestCursorColumnEntry(columnName = "reserved", value = "0"),
                TestCursorColumnEntry(columnName = "pri", value = "0"),
                TestCursorColumnEntry(columnName = "teleservice_id", value = "0"),
                TestCursorColumnEntry(columnName = "link_url", value = null),
                TestCursorColumnEntry(columnName = "svc_cmd", value = "0"),
                TestCursorColumnEntry(columnName = "svc_cmd_content", value = null),
                TestCursorColumnEntry(columnName = "roam_pending", value = "0"),
                TestCursorColumnEntry(columnName = "spam_report", value = "0"),
                TestCursorColumnEntry(columnName = "secret_mode", value = "0"),
                TestCursorColumnEntry(columnName = "safe_message", value = "0"),
                TestCursorColumnEntry(columnName = "favorite", value = "0"),
                TestCursorColumnEntry(columnName = "d_rpt_cnt", value = "0"),
                TestCursorColumnEntry(columnName = "using_mode", value = "0"),
                TestCursorColumnEntry(columnName = "from_address", value = null),
                TestCursorColumnEntry(columnName = "announcements_subtype", value = "0"),
                TestCursorColumnEntry(columnName = "announcements_scenario_id", value = null),
                TestCursorColumnEntry(columnName = "device_name", value = null),
                TestCursorColumnEntry(columnName = "correlation_tag", value = null),
                TestCursorColumnEntry(columnName = "object_id", value = null),
                TestCursorColumnEntry(columnName = "cmc_prop", value = null),
                TestCursorColumnEntry(columnName = "bin_info", value = "0"),
                TestCursorColumnEntry(columnName = "re_original_body", value = null),
                TestCursorColumnEntry(columnName = "re_body", value = null),
                TestCursorColumnEntry(columnName = "re_original_key", value = null),
                TestCursorColumnEntry(columnName = "re_recipient_address", value = null),
                TestCursorColumnEntry(columnName = "re_content_uri", value = null),
                TestCursorColumnEntry(columnName = "re_content_type", value = null),
                TestCursorColumnEntry(columnName = "re_file_name", value = null),
                TestCursorColumnEntry(columnName = "re_type", value = "0"),
                TestCursorColumnEntry(columnName = "re_count_info", value = null)
            )
        )
    )
}