name: Build and Tests

on:
  push:
    branches: [ "develop", "master" ]
  pull_request: null # Runs everytime a PR is opened

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Setting up JDK 17"
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - run: echo "Building..."
      - name: Build with Gradle Wrapper
        run: ./gradlew build assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: app/build/outputs/apk/debug/app-debug.apk

      - run: echo "Running unit tests..."
      - name: Unit Test
        run: ./gradlew testDebugUnitTest --stacktrace